#!/usr/bin/env python3
"""Regenerate supabase/seeds/archetypes.sql from the `archetypes` table.

The classifier rules are curated in the app (/:format/archetypes), so the
database — not the seed file — is where they actually evolve. This dumps the
current table back out as the committed fixture that ``supabase db reset``
reloads, instead of hand-patching the seed to match:

    python scripts/dump_archetypes.py
    DATABASE_URL="$SUPABASE_DB_URL" python scripts/dump_archetypes.py

Stdlib only; DB access is delegated to the ``psql`` CLI, like the other scripts.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from ingest_tournaments import LOCAL_DB_URL, ROOT, lit, load_env  # noqa: E402

SEED_PATH = ROOT / "supabase" / "seeds" / "archetypes.sql"
COLUMNS = ("format", "name", "sort_order", "min_signatures", "signature_cards", "required_cards", "excluded_cards")

HEADER = """\
-- Archetype classifier definitions (schema: supabase/schemas/archetypes.sql).
-- GENERATED by scripts/dump_archetypes.py — the rules are curated in-app at
-- /:format/archetypes, so the database is the source of truth and this is the
-- snapshot `supabase db reset` reloads. Re-run the script after editing rules;
-- hand-edits here are overwritten. Loaded after formats.sql (its only
-- dependency), and the classifier itself is built by seeds/refresh_archetypes.sql.
--
-- Cards are named by exact `cards.name`; a name absent from the dataset never
-- matches. min_signatures counts signature_cards and required_cards together,
-- null meaning "every one of them".
"""

# One row per archetype, ordered as the app lists them.
QUERY = """
select coalesce(json_agg(r), '[]') from (
  select a.format, f.name as format_name, a.name, a.sort_order, a.min_signatures,
         a.signature_cards, a.required_cards, a.excluded_cards
  from archetypes a join formats f on f.code = a.format
  order by f.sort_order, a.sort_order nulls last, a.name
) r
"""


def array_lit(values: list[str]) -> str:
    return "array[" + ", ".join(lit(v) for v in values) + "]" if values else "'{}'"


def num(value) -> str:
    return "null" if value is None else str(value)


def render(rows: list[dict]) -> str:
    out = [HEADER]
    for fmt in dict.fromkeys(r["format"] for r in rows):
        group = [r for r in rows if r["format"] == fmt]
        # The two rarely-used card lists only earn a column when the format uses them.
        extra = [c for c in ("required_cards", "excluded_cards") if any(r[c] for r in group)]
        columns = ("format", "name", "sort_order", "min_signatures", "signature_cards", *extra)
        # Pad the fixed-width columns so the trailing card arrays line up.
        name_w = max(len(lit(r["name"])) for r in group) + 1
        values = [
            f"  ({lit(r['format'])}, {lit(r['name']) + ',':<{name_w}} {num(r['sort_order']):>4},"
            f" {num(r['min_signatures']):>4}, "
            + ", ".join(array_lit(r[c]) for c in ("signature_cards", *extra))
            + ")"
            for r in group
        ]
        out.append(
            f"-- {group[0]['format_name']} ({len(group)} archetypes)\n"
            f"insert into archetypes ({', '.join(columns)}) values\n"
            + ",\n".join(values) + ";\n"
        )
    return "\n".join(out)


def main() -> None:
    load_env()
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--db-url", default=os.environ.get("DATABASE_URL", LOCAL_DB_URL), help="source DB (default: $DATABASE_URL or local)")
    p.add_argument("--output", type=Path, default=SEED_PATH)
    args = p.parse_args()

    out = subprocess.run(["psql", args.db_url, "-tAc", QUERY], capture_output=True, text=True, check=True).stdout
    rows = json.loads(out)
    if not rows:
        sys.exit("no archetypes in the database — refusing to write an empty seed")
    args.output.write_text(render(rows), encoding="utf-8")
    print(f"wrote {len(rows)} archetypes to {args.output.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
