#!/usr/bin/env python3
"""Refresh MTGO prices in goatbots_prices from Goatbots' published price file.

Downloads the daily price dump linked from https://www.goatbots.com/download-prices
(a zip holding one JSON object of MTGO catalog id -> sell price in tix) and
rewrites the goatbots_prices table in a single transaction. Foil and nonfoil
versions have distinct catalog ids; ids that match no printing are harmless and
kept, so the refresh needs no card data. Rewriting the whole table makes reruns
idempotent.

Same shape as ingest_tournaments.py: stdlib only, DB access via the psql CLI,
targets $DATABASE_URL (or the local stack by default), and ``--snapshot`` also
writes supabase/seeds/goatbots_prices.sql so ``supabase db reset`` reloads the
last ingested prices.

Note: Goatbots sits behind Cloudflare, which challenges curl's TLS fingerprint
but passes urllib with a descriptive User-Agent.
"""

from __future__ import annotations

import argparse
import io
import json
import os
import subprocess
import sys
import urllib.request
import zipfile
from pathlib import Path

PRICES_URL = "https://www.goatbots.com/download/prices/price-history.zip"
USER_AGENT = "manaring-goatbots-ingest/1.0 (https://github.com/mtgred/mtg)"
LOCAL_DB_URL = "postgresql://postgres:postgres@127.0.0.1:54322/postgres"
ROOT = Path(__file__).resolve().parent.parent
SEED_PATH = ROOT / "supabase" / "seeds" / "goatbots_prices.sql"
BATCH = 10_000  # rows per INSERT statement


def fetch_prices() -> dict[str, float]:
    req = urllib.request.Request(PRICES_URL, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req) as resp:
        payload = resp.read()
    with zipfile.ZipFile(io.BytesIO(payload)) as zf:
        return json.loads(zf.read(zf.namelist()[0]))


def prices_sql(prices: dict[str, float]) -> str:
    rows = sorted((int(mtgo_id), tix) for mtgo_id, tix in prices.items())
    inserts = [
        "INSERT INTO goatbots_prices (mtgo_id, tix) VALUES\n"
        + ",\n".join(f"({mtgo_id},{tix})" for mtgo_id, tix in rows[i : i + BATCH])
        + ";"
        for i in range(0, len(rows), BATCH)
    ]
    return "begin;\nTRUNCATE goatbots_prices;\n" + "\n".join(inserts) + "\ncommit;\n"


def apply_sql(sql: str, db_url: str) -> None:
    subprocess.run(
        ["psql", db_url, "-v", "ON_ERROR_STOP=1", "-q", "-f", "-"],
        input=sql,
        text=True,
        check=True,
    )


def write_snapshot(sql: str, count: int) -> None:
    header = (
        "-- Goatbots MTGO prices, generated by scripts/ingest_goatbots_prices.py --snapshot.\n"
        f"-- {count} MTGO catalog items. Self-contained (keyed by mtgo_id, no card joins);\n"
        "-- the full-table rewrite makes a `supabase db reset` reload idempotent.\n\n"
    )
    SEED_PATH.write_text(header + sql, encoding="utf-8")
    print(f"Wrote {SEED_PATH} ({count} items).", file=sys.stderr)


def main(argv=None):
    p = argparse.ArgumentParser(description="Refresh MTGO prices from Goatbots.")
    p.add_argument("--db-url", default=os.environ.get("DATABASE_URL", LOCAL_DB_URL), help="target DB (default: $DATABASE_URL or local)")
    p.add_argument("--snapshot", action="store_true", help="also write supabase/seeds/goatbots_prices.sql")
    p.add_argument("--dry-run", action="store_true", help="print SQL instead of applying it")
    args = p.parse_args(argv)

    print(f"Fetching {PRICES_URL}...", file=sys.stderr)
    prices = fetch_prices()
    sql = prices_sql(prices)

    if args.dry_run:
        sys.stdout.write(sql)
    else:
        apply_sql(sql, args.db_url)
        print(f"Applied {len(prices)} prices to {args.db_url.split('@')[-1]}.", file=sys.stderr)
    if args.snapshot:
        write_snapshot(sql, len(prices))


if __name__ == "__main__":
    main()
